server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties.hibernate:
      dialect: com.nujackpot.app.core.rdb.entity.product.CustomMySQLDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # h2 문법 mysql 변경