spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:mydb;MODE=MYSQL
    username: sa
    password: abcde
    driverClassName: org.h2.Driver

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'abcde'

logging:
#  config: classpath:logback/logback-dev.xml
